// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr6GQsGbi_QcoMl9-UiXlhsD5KUsQ2XYA',
    appId: '1:568990389373:web:bafdc23a21e1da895dcd14',
    messagingSenderId: '568990389373',
    projectId: 'prakflutterfirebase-d9075',
    authDomain: 'prakflutterfirebase-d9075.firebaseapp.com',
    storageBucket: 'prakflutterfirebase-d9075.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVVvYVXsUmW9GG0EP_5WTo4Ys3TwoY8jc',
    appId: '1:568990389373:android:8aa79090d31711495dcd14',
    messagingSenderId: '568990389373',
    projectId: 'prakflutterfirebase-d9075',
    storageBucket: 'prakflutterfirebase-d9075.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcHIF8tShf9Zp8mFTrySv7dvN4XuOSIMI',
    appId: '1:568990389373:ios:767b6c7787ab91285dcd14',
    messagingSenderId: '568990389373',
    projectId: 'prakflutterfirebase-d9075',
    storageBucket: 'prakflutterfirebase-d9075.appspot.com',
    iosBundleId: 'com.example.firebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcHIF8tShf9Zp8mFTrySv7dvN4XuOSIMI',
    appId: '1:568990389373:ios:767b6c7787ab91285dcd14',
    messagingSenderId: '568990389373',
    projectId: 'prakflutterfirebase-d9075',
    storageBucket: 'prakflutterfirebase-d9075.appspot.com',
    iosBundleId: 'com.example.firebaseAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCr6GQsGbi_QcoMl9-UiXlhsD5KUsQ2XYA',
    appId: '1:568990389373:web:7de1e14c85ba94f15dcd14',
    messagingSenderId: '568990389373',
    projectId: 'prakflutterfirebase-d9075',
    authDomain: 'prakflutterfirebase-d9075.firebaseapp.com',
    storageBucket: 'prakflutterfirebase-d9075.appspot.com',
  );
}
